services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    networks:
      - minipki
    volumes:
      - ./data:/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - STORAGE__DATAPATH=/data
      - Auth__PasswordHash=pbkdf2-sha256:100000:ClqEblBhH4AISgW25pIdxg==:UP5U7Xl3DITBqbxC5wbyq/BOSZ7br
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "22280:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - minipki
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  minipki:
    driver: bridge
