apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minipki-data
  namespace: minipki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
